version: '3'
services:

  luxonis-db:
    restart: always
    image: "postgres:9.6-alpine"
    container_name: luxonis-db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=luxon-db

  luxonis-be:
    build: ./luxonis-test-be
    container_name: luxonis-be
    ports:
      - 5000:5000
    links:
      - luxonis-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@luxonis-db:5432/luxon-db?schema=public

  luxonis-fe:
    build: ./luxonis-test-fe
    container_name: luxonis-fe
    ports:
      - 3000:80


volumes:
  data: